### ISSUE TITLE
Healthy Teens - title 

### ISSUE THREAD

**Issue by rax379** [rax379/final-project-vamv#14]
First thing was title is missing tweens on main page.

**Comment by rax379** [comment]
need introduction on main page leading me into module and what to expect

**Comment by rax379** [comment]
Main page goes right into nutrition - set up module with strong video and introduction, statistics or something that will engage me in wanting to continue finding out about healthy lifestyles for teens and tweens

**Comment by rax379** [comment]
on side maybe add a introduction link that talks about issues and that is where you can show the  video

**Comment by adriheard** [comment]
1)  Title is focus on teens 2) We have added a picture and a main page.  We will add statistics 3)  We added a introduction link.
