### ISSUE TITLE
Quiz Page - Functionality & Grammar

### ISSUE THREAD

**Issue by chente223** [rax379/final-project-vamv#54]
The "Audio" and "Captions" bar are covering the questions and appear to need to be placed more on the left of the Quiz questions.  This does not allow you to answer the questions that are covered up.  Which were #2,3,4.

Question for has grammar error "..should your fill your plate.." should probably read "...should you fill your plate...".

When answers were submitted a popup box saying "Hello!!" and when clicked "OK" button nothing seemed to happen.  Not sure if this is was the intention or not?

**Comment by aal740** [comment]
Captions and audio have been moved, grammar checked and the correct response now pop ups after submitting quiz.
