### ISSUE TITLE
Nutrition intro Header image link Broken

### ISSUE THREAD

**Issue by adriheard** [rax379/final-project-vamv#66]
![screen shot 2015-11-12 at 6 18 37 pm](https://cloud.githubusercontent.com/assets/14211321/11135345/d4759762-8969-11e5-92be-70f50e6db5af.png)

**Comment by adriheard** [comment]
It is an issue in SCORMcloud throughout the entire nutrition section.

**Comment by aal740** [comment]
headers have been changed and fixed to fit page
