### ISSUE TITLE
References are messed up 

### ISSUE THREAD

**Issue by adriheard** [rax379/final-project-vamv#74]
the word "references" is on the same line as the image and then the links are on the line below.

Noted on the following pages:

![screen shot 2015-11-12 at 6 35 36 pm](https://cloud.githubusercontent.com/assets/14211321/11135594/356b1a0e-896c-11e5-9109-e0748f92f99a.png)
Sports
Benefits
Losing weight safely

**Comment by aal740** [comment]
references have been fixed on all the pages
