### ISSUE TITLE
Storyboard Review

### ISSUE THREAD

**Issue by rax379** [rax379/final-project-vamv#8]
Reviewing on Safari - Global - On all pages is an option to take go to the Quiz on the left side navigation - will this be grayed out until the learner has seen all of the previous pages?

**Comment by rax379** [comment]
Reviewing on Safari - Global - size of iframe needs to be increased to fit page to prevent scrolling horizontally and vertically - might be an issue with placement of <div> </div>

**Comment by rax379** [comment]
Reviewing on Safari - Global - On all pages the middle and bottom of the iframe states "Next Topic or Subtopic:" and then in a box underneath this box is the actual next topic. Perhaps you would want to review how many times to state the words in the top box and in the bottom using images to illustrate the next topic. However, I wouldn’t make the bottom box bigger than the top box that is actually reviewing the main topic/subtopic. (Text/Video box for topic discussing is smaller than the box discussing the next topic).

**Comment by rax379** [comment]
Reviewing on Safari - Global - On all pages the middle and bottom of the iframe states "Next Topic or Subtopic:" and then in a box underneath this box is the actual next topic. Perhaps you would want to review how many times to state the words in the top box and in the bottom using images to illustrate the next topic. However, I wouldn’t make the bottom box bigger than the top box that is actually reviewing the main topic/subtopic. (Text/Video box for topic discussing is smaller than the box discussing the next topic).

**Comment by adriheard** [comment]
The quiz will be grayed out until beta.  The pages have been adjusted.
